import Foundation

// Generated by scripts/curriculum/gen.py — do not edit by hand.
//
// What a qualification assesses, and what each piece is worth. Bundled rather
// than fetched: subject selection has to work on a plane, and this never
// changes between releases.
//
// **What is deliberately not here.** Band descriptors — the prose explaining
// what 5-6 marks looks like — are the exam board's copyrighted assessment
// material. What is here is factual: component names, durations, marks,
// weightings, assessment objective codes. That is also what a planner actually
// needs; it turns into steps and time estimates. Descriptors would not.
//
// The server holds the same data and is what grounds a generated plan. This
// copy drives the UI. See gen.py for why they are separate.

struct CurriculumSubject: Identifiable, Hashable, Sendable {
    let code: String
    let qualification: Qualification
    /// Exam board. A-level assessment genuinely differs between boards, so this
    /// is part of a subject's identity rather than decoration. Nil where the
    /// qualification has a single authority, as the IB does.
    let board: String?
    let subject: String
    let specCode: String?
    let objectives: [Objective]
    let components: [Component]
    let notes: [String]
    /// Where the figures came from, so a revised specification can be re-checked
    /// against the exact page rather than re-researched from nothing.
    let source: String
    let retrievedAt: String

    var id: String { code }

    enum Qualification: String, CaseIterable, Sendable {
        case aLevel = "A_LEVEL"
        case ibDP = "IB_DP"
        case ap = "AP"
        case other = "OTHER"

        var title: String {
            switch self {
            case .aLevel: "A-Level"
            case .ibDP: "IB Diploma"
            case .ap: "Advanced Placement"
            case .other: "Other"
            }
        }
    }

    struct Objective: Hashable, Sendable {
        let code: String
        let name: String
        let weightingMin: Int?
        let weightingMax: Int?

        /// "30-35%", or "35%" when a board publishes a single figure.
        var weightingText: String? {
            switch (weightingMin, weightingMax) {
            case let (lo?, hi?) where lo != hi: "\(lo)-\(hi)%"
            case let (lo?, _): "\(lo)%"
            default: nil
            }
        }
    }

    struct Component: Identifiable, Hashable, Sendable {
        let code: String
        let name: String
        let kind: Kind
        let minutes: Int?
        let marks: Int?
        let weighting: Double
        /// SL / HL for the IB. Nil where a qualification has one level.
        let level: String?
        let covers: String?
        let format: String?
        let criteria: [Criterion]

        var id: String { code }

        enum Kind: String, Hashable, Sendable {
            case exam, coursework, practical, oral
            case internalAssessment = "internal_assessment"

            /// What a student calls it.
            var title: String {
                switch self {
                case .exam: "Exam"
                case .coursework: "Coursework"
                case .practical: "Practical"
                case .oral: "Oral"
                case .internalAssessment: "Internal assessment"
                }
            }
        }
    }

    struct Criterion: Identifiable, Hashable, Sendable {
        let code: String
        let name: String
        let marks: Int?
        /// Our own one-line note on what this criterion rewards — written here,
        /// never lifted from the official descriptor.
        let guidance: String?

        var id: String { code }
    }
}

extension CurriculumSubject {
    /// Every subject we have verified assessment data for.
    static let all: [CurriculumSubject] = [
        .init(
            code: "AQA_ALEVEL_BIOLOGY",
            qualification: .aLevel,
            board: "AQA",
            subject: "Biology",
            specCode: "7402",
            objectives: [
        .init(code: "AO1", name: "Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures", weightingMin: 30, weightingMax: 35),         .init(code: "AO2", name: "Apply knowledge and understanding of scientific ideas, processes, techniques and procedures", weightingMin: 40, weightingMax: 45),         .init(code: "AO3", name: "Analyse, interpret and evaluate scientific information, ideas and evidence", weightingMin: 25, weightingMax: 30)
            ],
            components: [
            .init(code: "PAPER_1", name: "Paper 1", kind: .exam, minutes: 120, marks: 91, weighting: 35, level: nil, covers: "Topics 1-4, including relevant practical skills", format: "76 marks of short and long answer questions; 15 marks of extended response", criteria: []),
            .init(code: "PAPER_2", name: "Paper 2", kind: .exam, minutes: 120, marks: 91, weighting: 35, level: nil, covers: "Topics 5-8, including relevant practical skills", format: "76 marks of short and long answer questions; 15 marks comprehension", criteria: []),
            .init(code: "PAPER_3", name: "Paper 3", kind: .exam, minutes: 120, marks: 78, weighting: 30, level: nil, covers: "Topics 1-8, including relevant practical skills", format: "38 marks structured including practical techniques; 15 marks critical analysis of experimental data; 25 marks one essay from a choice of two", criteria: [])
            ],
            notes: ["Assessment objectives are set by Ofqual and are identical across every board's A-level Biology; only the weightings differ.", "At least 15% of the overall assessment covers knowledge, skills and understanding in relation to practical work.", "10% of the overall assessment contains mathematical skills at Level 2 or above.", "Syllabus topics remain unverified: the complete topic outline in this record’s AQA specification has not been checked for this corpus. IB pages cannot verify an AQA syllabus."],
            source: "https://filestore.aqa.org.uk/resources/biology/specifications/AQA-7401-7402-SP-2015.PDF",
            retrievedAt: "2026-08-24"
        ),
        .init(
            code: "AQA_ALEVEL_CHEMISTRY",
            qualification: .aLevel,
            board: "AQA",
            subject: "Chemistry",
            specCode: "7405",
            objectives: [
        .init(code: "AO1", name: "Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures", weightingMin: 30, weightingMax: 30),         .init(code: "AO2", name: "Apply knowledge and understanding of scientific ideas, processes, techniques and procedures", weightingMin: 45, weightingMax: 45),         .init(code: "AO3", name: "Analyse, interpret and evaluate scientific information, ideas and evidence", weightingMin: 25, weightingMax: 25)
            ],
            components: [
            .init(code: "PAPER_1", name: "Paper 1", kind: .exam, minutes: 120, marks: 105, weighting: 35, level: nil, covers: "Relevant physical chemistry topics, inorganic chemistry, and relevant practical skills", format: "105 marks of short and long answer questions", criteria: []),
            .init(code: "PAPER_2", name: "Paper 2", kind: .exam, minutes: 120, marks: 105, weighting: 35, level: nil, covers: "Relevant physical chemistry topics, organic chemistry, and relevant practical skills", format: "105 marks of short and long answer questions", criteria: []),
            .init(code: "PAPER_3", name: "Paper 3", kind: .exam, minutes: 120, marks: 90, weighting: 30, level: nil, covers: nil, format: nil, criteria: [])
            ],
            notes: ["Assessment objectives are set by Ofqual and are identical across every board's A-level Chemistry; only the weightings differ.", "20% of the overall assessment contains mathematical skills at Level 2 or above.", "At least 15% of the overall assessment covers practical work.", "Syllabus topics remain unverified: the complete topic outline in this record’s AQA specification has not been checked for this corpus. IB pages cannot verify an AQA syllabus."],
            source: "https://filestore.aqa.org.uk/resources/chemistry/specifications/AQA-7404-7405-SP-2015.PDF",
            retrievedAt: "2026-08-24"
        ),
        .init(
            code: "AQA_ALEVEL_PHYSICS",
            qualification: .aLevel,
            board: "AQA",
            subject: "Physics",
            specCode: "7408",
            objectives: [
        .init(code: "AO1", name: "Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures", weightingMin: 33, weightingMax: 33),         .init(code: "AO2", name: "Apply knowledge and understanding of scientific ideas, processes, techniques and procedures", weightingMin: 42, weightingMax: 42),         .init(code: "AO3", name: "Analyse, interpret and evaluate scientific information, ideas and evidence", weightingMin: 25, weightingMax: 25)
            ],
            components: [
            .init(code: "PAPER_1", name: "Paper 1", kind: .exam, minutes: 120, marks: 85, weighting: 34, level: nil, covers: "Sections 1-5 and 6.1 (Periodic motion)", format: "60 marks of short and long answer questions and 25 multiple choice questions", criteria: []),
            .init(code: "PAPER_2", name: "Paper 2", kind: .exam, minutes: 120, marks: 85, weighting: 34, level: nil, covers: nil, format: nil, criteria: []),
            .init(code: "PAPER_3", name: "Paper 3", kind: .exam, minutes: 120, marks: 80, weighting: 32, level: nil, covers: nil, format: nil, criteria: [])
            ],
            notes: ["Assessment objectives are set by Ofqual and are identical across every board's A-level Physics; only the weightings differ.", "40% of the overall assessment contains mathematical skills at Level 2 or above.", "At least 15% of the overall assessment covers practical work.", "Paper 3 includes an options section; students answer on one option from sections 9-13.", "Syllabus topics remain unverified: the complete topic outline in this record’s AQA specification has not been checked for this corpus. IB pages cannot verify an AQA syllabus."],
            source: "https://filestore.aqa.org.uk/resources/physics/specifications/AQA-7407-7408-SP-2015.PDF",
            retrievedAt: "2026-08-24"
        ),
        .init(
            code: "IB_DP_BIOLOGY",
            qualification: .ibDP,
            board: nil,
            subject: "Biology",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Show that you know the subject’s facts, vocabulary and ideas, as well as its practical skills and methods.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Use your understanding of the subject’s ideas and vocabulary to choose and apply suitable skills and methods.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Examine experimental methods and data you collect or obtain from other sources; judge their quality and bring the evidence together to explain patterns and make predictions.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Use your practical and analytical skills to investigate a worthwhile question, making responsible ethical choices throughout.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Scientific investigation (SL)", kind: .internalAssessment, minutes: 600, marks: 24, weighting: 20, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research design", marks: 6, guidance: "State the question with its variables and enough method to repeat."), .init(code: "B", name: "Data analysis", marks: 6, guidance: "Record, process and present data so a conclusion can be drawn, uncertainties included."), .init(code: "C", name: "Conclusion", marks: 6, guidance: "Answer your own question against the analysis and published science, uncertainties included."), .init(code: "D", name: "Evaluation", marks: 6, guidance: "Name the specific weaknesses that mattered most and improvements that address them.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Scientific investigation (HL)", kind: .internalAssessment, minutes: 600, marks: 24, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research design", marks: 6, guidance: "State the question with its variables and enough method to repeat."), .init(code: "B", name: "Data analysis", marks: 6, guidance: "Record, process and present data so a conclusion can be drawn, uncertainties included."), .init(code: "C", name: "Conclusion", marks: 6, guidance: "Answer your own question against the analysis and published science, uncertainties included."), .init(code: "D", name: "Evaluation", marks: 6, guidance: "Name the specific weaknesses that mattered most and improvements that address them.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["Identical IA across Biology, Chemistry and Physics under the first-assessment-2025 guides.", "Report maximum 3,000 words; tables, calculations, citations, graphs and appendices are excluded.", "Conclusion and Evaluation are together half the marks.", "Figures taken from the Albus IB knowledge base v1.0 (compiled August 2026), which paraphrases the official IB subject guides rather than reproducing them. Verify against the current guide before quoting marks to a student.", "Syllabus topics contain only the four organizing themes visible in the official page’s curriculum figure. The figure leaves individual topic nodes blank; their names and SL/HL scope are not confirmed here. First teaching 2023 matches the first-assessment-2025 specification.", "AO1–AO4 are Albus’s own second-person paraphrases of the matching 2025 assessment objectives, checked in two independently hosted IB publications. The brief gives component weightings, not separate per-AO percentages, so objective weights remain null. These are subject-wide objectives; AO4 concerns investigation skills, not a claim that every exam paper separately assesses them."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-08-25"
        ),
        .init(
            code: "IB_DP_BUSINESS",
            qualification: .ibDP,
            board: nil,
            subject: "Business management",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Show that you understand business tools, theories and course concepts, and can explain the problems and choices businesses face; include extension topics only if you take HL.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Use business tools and concepts to analyse a problem or decision, choosing data that help you examine the issue; apply HL extensions only at HL.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Bring business ideas and evidence together, weigh stakeholder interests and judge decisions; at HL, also compare competing strategic directions and justify your recommendation.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Choose suitable tools and concepts to investigate a business problem, examine evidence from original and existing sources, and present organised work using precise business terminology.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Business research project (SL)", kind: .internalAssessment, minutes: 1200, marks: 25, weighting: 30, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 70, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Business research project (HL)", kind: .internalAssessment, minutes: 1200, marks: 25, weighting: 20, level: "HL", covers: nil, format: nil, criteria: []),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["Maximum 1,800 words; only the first 1,800 are marked.", "One real organisation, and exactly one of change, creativity, ethics or sustainability as the lens.", "Three to five supporting documents must be attached.", "25 marks across SEVEN criteria A-G, common to SL and HL under the 2024 guide. Both figures are corroborated: knowledge base 7.7 [OFFICIAL] and two independent sources give 25, and a published grader rubric plus a second source both reference a Criterion G. The earlier claim of four criteria totalling 20 marks is the outlier and is now ruled out.", "The per-criterion SPLIT is still not publishable. The one source that lists all seven marks sums them to 27, not its own stated 25, and sources disagree on whether criterion A is the key concept or the context. Corroborated fragments only: key concept 5, supporting documents 4, presentation 2.", "The official IB subject brief confirms the component (20 hours, 20% at HL) but carries no per-criterion marks, as subject briefs never do.", "The public ibo.org subject page still describes the pre-2024 structure despite a 2026 'last updated' date — do not source from it.", "Topic and objective coverage comes from matching first-assessment-2024 IB briefs in two independent school collections, not the public Business page that still describes the preceding structure. HL-only topic labels and objective scope are retained; research-time and assessment-time allocations are not syllabus topics.", "The briefs publish AO1–AO4 but no per-objective percentage ranges, so objective weightings remain null. These objectives do not establish per-criterion marks; the deliberately empty criteria and their documented contradictions remain unchanged."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_CHEMISTRY",
            qualification: .ibDP,
            board: nil,
            subject: "Chemistry",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Show that you know the subject’s facts, vocabulary and ideas, as well as its practical skills and methods.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Use your understanding of the subject’s ideas and vocabulary to choose and apply suitable skills and methods.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Examine experimental methods and data you collect or obtain from other sources; judge their quality and bring the evidence together to explain patterns and make predictions.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Use your practical and analytical skills to investigate a worthwhile question, making responsible ethical choices throughout.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Scientific investigation (SL)", kind: .internalAssessment, minutes: 600, marks: 24, weighting: 20, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research design", marks: 6, guidance: "State the question with its variables and enough method to repeat."), .init(code: "B", name: "Data analysis", marks: 6, guidance: "Record, process and present data so a conclusion can be drawn, uncertainties included."), .init(code: "C", name: "Conclusion", marks: 6, guidance: "Answer your own question against the analysis and published science, uncertainties included."), .init(code: "D", name: "Evaluation", marks: 6, guidance: "Name the specific weaknesses that mattered most and improvements that address them.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Scientific investigation (HL)", kind: .internalAssessment, minutes: 600, marks: 24, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research design", marks: 6, guidance: "State the question with its variables and enough method to repeat."), .init(code: "B", name: "Data analysis", marks: 6, guidance: "Record, process and present data so a conclusion can be drawn, uncertainties included."), .init(code: "C", name: "Conclusion", marks: 6, guidance: "Answer your own question against the analysis and published science, uncertainties included."), .init(code: "D", name: "Evaluation", marks: 6, guidance: "Name the specific weaknesses that mattered most and improvements that address them.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["Identical IA across Biology, Chemistry and Physics under the first-assessment-2025 guides.", "Report maximum 3,000 words; tables, calculations, citations, graphs and appendices are excluded.", "Conclusion and Evaluation are together half the marks.", "Figures taken from the Albus IB knowledge base v1.0 (compiled August 2026), which paraphrases the official IB subject guides rather than reproducing them. Verify against the current guide before quoting marks to a student.", "The public syllabus table confirms organizing concepts and six headings, not individual subtopics or their SL/HL scope. First teaching 2023 matches the first-assessment-2025 specification.", "AO1–AO4 are Albus’s own second-person paraphrases of the matching 2025 assessment objectives, checked in two independently hosted IB publications. The brief gives component weightings, not separate per-AO percentages, so objective weights remain null. These are subject-wide objectives; AO4 concerns investigation skills, not a claim that every exam paper separately assesses them."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-08-25"
        ),
        .init(
            code: "IB_DP_COMPSCI",
            qualification: .ibDP,
            board: nil,
            subject: "Computer science",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Show that you understand computing facts, concepts, principles and vocabulary, and the methods and skills used to solve problems through computational thinking.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Use your computing knowledge and computational thinking methods to solve problems, and choose suitable ways to present computing information.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Develop and assess problem specifications, system requirements, success criteria, test strategies and programs. Analyse the techniques, evidence and technical explanations supporting your solution.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Apply computational thinking to build computing solutions for problems in the real world.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Computational solution (SL)", kind: .internalAssessment, minutes: 2100, marks: 30, weighting: 30, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Problem specification", marks: 4, guidance: "Define the problem and give requirements specific enough to test the finished thing against."), .init(code: "B", name: "Planning", marks: 4, guidance: "Show the design decisions and why you made them, not just what you built."), .init(code: "C", name: "System overview", marks: 6, guidance: "How the parts fit together. Diagrams that a reader could rebuild the structure from."), .init(code: "D", name: "Development", marks: 12, guidance: "The largest criterion and the only one assessing the product. Show techniques, not just working code."), .init(code: "E", name: "Evaluation", marks: 4, guidance: "Test against your own criterion A requirements, and say what you would do differently.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 70, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Computational solution (HL)", kind: .internalAssessment, minutes: 2100, marks: 30, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Problem specification", marks: 4, guidance: "Define the problem and give requirements specific enough to test the finished thing against."), .init(code: "B", name: "Planning", marks: 4, guidance: "Show the design decisions and why you made them, not just what you built."), .init(code: "C", name: "System overview", marks: 6, guidance: "How the parts fit together. Diagrams that a reader could rebuild the structure from."), .init(code: "D", name: "Development", marks: 12, guidance: "The largest criterion and the only one assessing the product. Show techniques, not just working code."), .init(code: "E", name: "Evaluation", marks: 4, guidance: "Test against your own criterion A requirements, and say what you would do differently.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["2027 guide: a 35-hour computational solution, 30 marks across five criteria, with a video submission alongside the documentation. 30% at SL, 20% at HL, same criteria at both levels.", "Applies from the May 2027 session. A November 2026 candidate is still on the previous guide (34 marks, different criteria) — check the student's exam session before quoting anything.", "Four of the five criteria assess process; only D assesses the finished product, with the video as the primary evidence of functionality.", "Scoping is the dominant failure: a modest system that demonstrably runs outscores an ambitious one that does not.", "The 2027 guide does not require a named client.", "The main subject page explicitly describes last assessment 2026 and must not supply topics for this record. The linked 2027 curriculum update supplies these headings; its assessment prose and table disagree on SL weighting, so no assessment figures are taken from it.", "AO1-AO4 are paraphrased from the first-assessment-2027 IB subject brief hosted by Mickiewicz Katowice and independently matched against Heidelberg International School’s 2026-28 handbook. Only the agreeing objective text is used from the handbook; its adjacent examination-duration table contains inconsistencies and is not a source for timing or weighting. Neither source publishes separate per-AO weightings, so these remain unknown."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_ECONOMICS",
            qualification: .ibDP,
            board: nil,
            subject: "Economics",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Show that you understand the economics you have studied and current economic evidence; include extension content if you take HL.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Apply economic ideas to actual situations, interpret the evidence and explain how it is being used. In your IA, connect each commentary to its key concept; at HL, also apply and analyse extension content.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Build and evaluate an economic argument using theory and examples. At HL, also evaluate extension content and use economic evidence to recommend policy.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Organize your writing with accurate economic terminology. Use diagrams, news extracts, data and calculations to explain and analyse economic relationships.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Portfolio of three commentaries (SL)", kind: .internalAssessment, minutes: 1200, marks: 45, weighting: 30, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Diagrams", marks: nil, guidance: "Accurate, labelled, and actually referred to in the text. A diagram nobody discusses earns little."), .init(code: "B", name: "Terminology", marks: nil, guidance: "Use the economic terms the article calls for, consistently, not once in the introduction."), .init(code: "C", name: "Application and analysis", marks: nil, guidance: "Explain the economics of this specific situation. Summarising the article is not application."), .init(code: "D", name: "Key concept", marks: nil, guidance: "One concept per commentary, integrated throughout — naming it and moving on forfeits the marks."), .init(code: "E", name: "Evaluation", marks: nil, guidance: "Stakeholders, short run versus long run, and assumptions. One-sided evaluation caps the mark.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 70, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Portfolio of three commentaries (HL)", kind: .internalAssessment, minutes: 1200, marks: 45, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Diagrams", marks: nil, guidance: "Accurate, labelled, and actually referred to in the text. A diagram nobody discusses earns little."), .init(code: "B", name: "Terminology", marks: nil, guidance: "Use the economic terms the article calls for, consistently, not once in the introduction."), .init(code: "C", name: "Application and analysis", marks: nil, guidance: "Explain the economics of this specific situation. Summarising the article is not application."), .init(code: "D", name: "Key concept", marks: nil, guidance: "One concept per commentary, integrated throughout — naming it and moving on forfeits the marks."), .init(code: "E", name: "Evaluation", marks: nil, guidance: "Stakeholders, short run versus long run, and assumptions. One-sided evaluation caps the mark.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["Three commentaries, each on a different published article, a different syllabus unit and a different key concept.", "Each commentary is 800 words maximum and marked out of 14 across five criteria; 3 further portfolio-level marks give a total of 45.", "Criterion NAMES are corroborated; the per-criterion mark split is NOT — sources disagree, so no marks are published.", "Articles must be from different sources and published within a year of the commentary.", "At SL this is 30% of the subject — the highest-weighted IA in group 3.", "Two independent school hosts of the matching IB briefs confirm four shared unit headings and AO1–AO4. The outline stops at units because the SL and HL subtopic lists differ; it does not imply identical depth at both levels.", "Objective descriptions are Albus’s own second-person paraphrases. HL extensions and policy recommendations retain their HL restriction, and the commentary requirement retains its IA scope. The briefs publish assessment-component percentages, not whole-subject per-AO ranges, so objective weights remain null."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_ESS",
            qualification: .ibDP,
            board: nil,
            subject: "Environmental systems and societies",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Show that you understand environmental concepts, methods and terminology, including the different perspectives people bring to an issue.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Use your understanding to analyse explanations, evidence, models and case studies, including the arguments and values involved.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Evaluate explanations, proposed solutions and investigation methods; justify your judgments and connect the political, economic, ethical and social contexts.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Investigate a sustainability issue by defining a workable environmental research question and using suitable methods ethically.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Individual investigation (SL)", kind: .internalAssessment, minutes: 600, marks: 30, weighting: 25, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research question and inquiry", marks: nil, guidance: "Name the environmental issue and the question, and show why it is worth investigating."), .init(code: "B", name: "Strategy and tension", marks: nil, guidance: "New in the 2026 guide and the differentiator. Show how competing perspectives change the outcome of a strategy."), .init(code: "C", name: "Method", marks: nil, guidance: "Appropriate to the question and repeatable by someone else from what you wrote."), .init(code: "D", name: "Treatment of data", marks: nil, guidance: "Process and present the data so it can be read, uncertainties included."), .init(code: "E", name: "Analysis and conclusion", marks: nil, guidance: "Interpret what the data shows and answer your own question, only as far as it supports."), .init(code: "F", name: "Evaluation", marks: nil, guidance: "Limitations that actually mattered, improvements that address them, and what is still open.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 75, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Individual investigation (HL)", kind: .internalAssessment, minutes: 600, marks: 30, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research question and inquiry", marks: nil, guidance: "Name the environmental issue and the question, and show why it is worth investigating."), .init(code: "B", name: "Strategy and tension", marks: nil, guidance: "New in the 2026 guide and the differentiator. Show how competing perspectives change the outcome of a strategy."), .init(code: "C", name: "Method", marks: nil, guidance: "Appropriate to the question and repeatable by someone else from what you wrote."), .init(code: "D", name: "Treatment of data", marks: nil, guidance: "Process and present the data so it can be read, uncertainties included."), .init(code: "E", name: "Analysis and conclusion", marks: nil, guidance: "Interpret what the data shows and answer your own question, only as far as it supports."), .init(code: "F", name: "Evaluation", marks: nil, guidance: "Limitations that actually mattered, improvements that address them, and what is still open.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["3,000 words maximum, up from 2,250 under the previous guide. 30 marks across six criteria A-F, common at SL and HL. Ten hours.", "Criterion NAMES are corroborated; the per-criterion split is NOT — one source gives 4/4/4/6/6/6, another states it is unpublished. No marks are claimed.", "Criterion B (strategy and tension) is new in the 2026 guide and has no legacy exemplars. Treating this as a Biology IA with an environmental topic forfeits it entirely.", "Group collaboration is permitted if variables differ and each student's data is their own.", "Two independently hosted matching IB briefs confirm eight syllabus topics, the three named Foundation subtopics and three HL-only lenses. The earlier absence note’s reference to seven topics was incorrect. Practical work and inquiry skills are integrated activities, not additional syllabus topics.", "AO1–AO4 are Albus’s own second-person paraphrases of the 2026 brief. AO4 concerns an ethical investigation of a sustainability issue; it is not evidence that each exam paper assesses all four objectives. The briefs give component percentages, not whole-subject per-AO weightings, so objective weights remain null."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_EXTENDED_ESSAY",
            qualification: .ibDP,
            board: nil,
            subject: "Extended essay",
            specCode: nil,
            objectives: [
        .init(code: "Albus 1", name: "Show that you understand your chosen topic and research question, the relevant terminology and concepts, and the research methods you use.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 2", name: "Apply suitable research methods to answer your question and analyse what your research reveals.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 3", name: "Weigh the significance of your findings and connect your question, findings and conclusions through a clear argument. Evaluate your essay and reflect on what the research experience has taught you as a learner.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 4", name: "Present your research using the appropriate structure and conventions, and show academic integrity throughout.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "ESSAY", name: "Extended essay", kind: .coursework, minutes: 2400, marks: 30, weighting: 100, level: nil, covers: nil, format: "4,000 words, graded A to E; contributes to the core points with TOK", criteria: [.init(code: "A", name: "Framework for the essay", marks: 6, guidance: "A genuine, focused question, methods that suit the subject, and a structure that follows its conventions."), .init(code: "B", name: "Knowledge and understanding", marks: 6, guidance: "Findings used to build subject knowledge, with accurate terminology and correct key concepts."), .init(code: "C", name: "Analysis and line of argument", marks: 6, guidance: "Evidence-backed findings joined by a signposted thread from question to conclusion."), .init(code: "D", name: "Discussion and evaluation", marks: 8, guidance: "The heaviest criterion: weigh the significance of findings and appraise your sources' strengths and limits."), .init(code: "E", name: "Reflection", marks: 4, guidance: "Assessed from the 500-word reflective statement, not the essay.")])
            ],
            notes: ["30 marks from May 2027; the legacy 34-mark model applies to November 2026 and earlier.", "Criterion D alone is 8 of 30 marks.", "An E in the extended essay is a failing condition for the diploma regardless of total points.", "Figures taken from the Albus IB knowledge base v1.0 (compiled August 2026), which paraphrases the official IB subject guides rather than reproducing them. Verify against the current guide before quoting marks to a student.", "The first-assessment-2027 IB brief hosted by the American International School in Cyprus and Heidelberg International School’s 2026-28 handbook agree on four named objective groups and their full scope. “Albus 1” through “Albus 4” are local identifiers preserving the source order, not official IB AO codes. No separate objective weightings are published. The brief describes a student-selected research topic and research process, not a prescribed syllabus topic list; syllabus topics remain empty and unverified rather than turning research stages or essay examples into a syllabus.", "The 2027 criterion names and 6/6/6/8/4 allocations are corroborated in two independently hosted matching IB guides. The former reference to a first-assessment-2018 guide was invalid provenance for these criteria; the verified 2027 allocations are retained, with confidence corroborated rather than a claim of direct official-site access."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-08-25"
        ),
        .init(
            code: "IB_DP_GEOGRAPHY",
            qualification: .ibDP,
            board: nil,
            subject: "Geography",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Knowledge and understanding of specified content", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Application and analysis of knowledge and understanding", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Synthesis and evaluation", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Selection, use and application of a variety of appropriate skills and techniques", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Fieldwork report (SL)", kind: .internalAssessment, minutes: 1200, marks: 25, weighting: 25, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Fieldwork question and geographic context", marks: nil, guidance: "Name the question, the place, and the syllabus theory it comes from — a question with no theory behind it caps this."), .init(code: "B", name: "Method(s) of investigation", marks: nil, guidance: "Say what you did and why that method suited the question, including how you sampled."), .init(code: "C", name: "Quality and treatment of information collected", marks: nil, guidance: "Every figure needs a title, units and a scale. Present data so it can be read, not just shown."), .init(code: "D", name: "Written analysis", marks: nil, guidance: "Interpret the graphs rather than describing them, and tie each finding back to the question."), .init(code: "E", name: "Conclusion", marks: nil, guidance: "Answer your own question directly, and only as far as the data supports."), .init(code: "F", name: "Evaluation", marks: nil, guidance: "Name the confounds that actually mattered — weather, time of day, sample size — and what you would change.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 75, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Fieldwork report (HL)", kind: .internalAssessment, minutes: 1200, marks: 25, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Fieldwork question and geographic context", marks: nil, guidance: "Name the question, the place, and the syllabus theory it comes from — a question with no theory behind it caps this."), .init(code: "B", name: "Method(s) of investigation", marks: nil, guidance: "Say what you did and why that method suited the question, including how you sampled."), .init(code: "C", name: "Quality and treatment of information collected", marks: nil, guidance: "Every figure needs a title, units and a scale. Present data so it can be read, not just shown."), .init(code: "D", name: "Written analysis", marks: nil, guidance: "Interpret the graphs rather than describing them, and tie each finding back to the question."), .init(code: "E", name: "Conclusion", marks: nil, guidance: "Answer your own question directly, and only as far as the data supports."), .init(code: "F", name: "Evaluation", marks: nil, guidance: "Name the confounds that actually mattered — weather, time of day, sample size — and what you would change.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["Maximum 2,500 words; exceeding it particularly damages the later criteria, because moderators are advised to stop reading.", "Six criteria A-F totalling 25 marks. The per-criterion split is NOT verified — criteria are published by name only, with no marks.", "Appendices should hold representative examples only, never every questionnaire and never secondary information.", "Superseded 2011 guide used 30 marks across seven criteria A-G; sources describing that split do not apply.", "Assessment objectives added from the official IB subject brief (no per-AO weighting is published there, so weightingMin/Max are left null; only Paper-level weightings are given and are already recorded above).", "The matching independently hosted IB briefs agree on seven optional themes, three common-core headings and three HL extension headings. Retain the choice structure: a student studies two optional themes at SL or three at HL, not all seven. These sources do not establish which options their school selected.", "The four existing objective names agree in both matching briefs and now carry explicit provenance. Their full descriptor prose is not expanded: the older Nord Anglia copy contains an unrelated film bullet under AO1 that is absent from the Living Academy copy. That discrepancy does not affect the four headings or the syllabus outline; no film content is used. Whole-subject objective weights remain unconfirmed and null."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_HISTORY",
            qualification: .ibDP,
            board: nil,
            subject: "History",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Use accurate, detailed historical knowledge and show that you understand the concepts, context and sources relevant to your question.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Build a clear argument supported by relevant historical knowledge, and analyse and interpret different kinds of sources.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Bring evidence and analysis together into a coherent answer. Weigh different historical perspectives, assess sources for their value and limitations, and combine information from relevant sources.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Develop focused essays and research questions, choose and reference suitable sources, and organise your research. Reflect on historians’ methods and the difficulties they face.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Historical investigation (SL)", kind: .internalAssessment, minutes: 1200, marks: 25, weighting: 25, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Identification and evaluation of sources", marks: 6, guidance: "Explain how each source's origin and purpose create its value and its limits, for this question."), .init(code: "B", name: "Investigation", marks: 15, guidance: "Critical analysis with evidence and differing perspectives, ending in a reasoned judgment."), .init(code: "C", name: "Reflection", marks: 4, guidance: "What your own investigation revealed about how historians work.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 75, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Historical investigation (HL)", kind: .internalAssessment, minutes: 1200, marks: 25, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Identification and evaluation of sources", marks: 6, guidance: "Explain how each source's origin and purpose create its value and its limits, for this question."), .init(code: "B", name: "Investigation", marks: 15, guidance: "Critical analysis with evidence and differing perspectives, ending in a reasoned judgment."), .init(code: "C", name: "Reflection", marks: 4, guidance: "What your own investigation revealed about how historians work.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["Maximum 2,200 words; bibliography and referencing sit outside the count.", "Section 2 carries 15 of the 25 marks.", "Same requirements at SL and HL; only the weighting differs.", "Figures taken from the Albus IB knowledge base v1.0 (compiled August 2026), which paraphrases the official IB subject guides rather than reproducing them. Verify against the current guide before quoting marks to a student.", "Guide currency RESOLVED. The replacement History guide is first taught August 2026 and first assessed May 2028, so the 2017 guide runs through May 2027 — the knowledge base was right and the official subject brief's 'last assessments 2025' was a stale projection from a 2015-vintage document that IB later extended. The published criteria (A 6 / B 15 / C 4 = 25, 2,200 words) are confirmed current by multiple 2025-26 sources. A candidate sitting May 2028 or later will need the new guide; nobody in the app today does.", "The public outline matches this record’s 2017 guide and last-assessment-2027 course, not the separately linked first-assessment-2028 replacement. Headings retain the choice structure: these are options, not a requirement to study every listed topic. The page does not specify which options a student’s school chose.", "The 2017-guide AO1-AO4 list agrees in the IB briefs hosted independently by Nord Anglia and Linz International School Auhof; Nord Anglia includes matching SL and HL objective sets. The briefs’ projected last-assessment-2025 label is stale for the already established extension through 2027, not evidence of a different objective set. These objectives are for the 2017 guide only; no 2028 objectives or separate per-AO weightings are inferred."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-08-25"
        ),
        .init(
            code: "IB_DP_LANG_A_LANGLIT",
            qualification: .ibDP,
            board: nil,
            subject: "Language A: language and literature",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Explain what the texts and works mean, including their implications; connect your interpretation to their writing and reception contexts, the craft used and the features of their forms.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Judge how language and artistic choices shape meaning and effects; compare texts and examine the views they offer on human concerns.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Present your ideas so your reader or listener can follow and assess a persuasive argument; adapt your style and register to the purpose and situation.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Individual oral (SL)", kind: .internalAssessment, minutes: 15, marks: 40, weighting: 30, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Knowledge, understanding and interpretation", marks: 10, guidance: "Show what the extracts mean and what they imply about your global issue — not what happens in them."), .init(code: "B", name: "Analysis and evaluation", marks: 10, guidance: "Explain how the author's choices build the global issue. Naming a device without its effect earns nothing."), .init(code: "C", name: "Focus and organization", marks: 10, guidance: "The global issue is the through-line, not a label. It should decide what you include and what you cut."), .init(code: "D", name: "Language", marks: 10, guidance: "Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 70, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Individual oral (HL)", kind: .internalAssessment, minutes: 15, marks: 40, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Knowledge, understanding and interpretation", marks: 10, guidance: "Show what the extracts mean and what they imply about your global issue — not what happens in them."), .init(code: "B", name: "Analysis and evaluation", marks: 10, guidance: "Explain how the author's choices build the global issue. Naming a device without its effect earns nothing."), .init(code: "C", name: "Focus and organization", marks: 10, guidance: "The global issue is the through-line, not a label. It should decide what you include and what you cut."), .init(code: "D", name: "Language", marks: 10, guidance: "Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["15 minutes: 10-minute presentation on one literary and one non-literary extract connected by a global issue, then 5 minutes of teacher questions.", "A global issue must be significant at scale, transnational, and visible in everyday local contexts.", "Works used for the individual oral may NOT be reused for the HL essay or for paper 2.", "Four criteria A-D at 10 marks each, total 40.", "The three syllabus headings are areas of exploration shared by SL and HL, not a prescribed reading list; the briefs do not identify the works selected by a school.", "Objectives 1–3 are paraphrased from matching 2021 IB briefs hosted independently by two schools. The communication bullet expressly limited to literature and performance is excluded because this record is a different course. The briefs give assessment-component percentages, not per-objective weights; objective weightings remain null."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_LANG_A_LIT",
            qualification: .ibDP,
            board: nil,
            subject: "Language A: literature",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Explain what the texts and works mean, including their implications; connect your interpretation to their writing and reception contexts, the craft used and the features of their forms.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Judge how language and artistic choices shape meaning and effects; compare texts and examine the views they offer on human concerns.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Present your ideas so your reader or listener can follow and assess a persuasive argument; adapt your style and register to the purpose and situation.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Individual oral (SL)", kind: .internalAssessment, minutes: 15, marks: 40, weighting: 30, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Knowledge, understanding and interpretation", marks: 10, guidance: "Show what the extracts mean and what they imply about your global issue — not what happens in them."), .init(code: "B", name: "Analysis and evaluation", marks: 10, guidance: "Explain how the author's choices build the global issue. Naming a device without its effect earns nothing."), .init(code: "C", name: "Focus and organization", marks: 10, guidance: "The global issue is the through-line, not a label. It should decide what you include and what you cut."), .init(code: "D", name: "Language", marks: 10, guidance: "Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 70, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Individual oral (HL)", kind: .internalAssessment, minutes: 15, marks: 40, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Knowledge, understanding and interpretation", marks: 10, guidance: "Show what the extracts mean and what they imply about your global issue — not what happens in them."), .init(code: "B", name: "Analysis and evaluation", marks: 10, guidance: "Explain how the author's choices build the global issue. Naming a device without its effect earns nothing."), .init(code: "C", name: "Focus and organization", marks: 10, guidance: "The global issue is the through-line, not a label. It should decide what you include and what you cut."), .init(code: "D", name: "Language", marks: 10, guidance: "Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["15 minutes: 10-minute presentation on two literary works connected by a global issue, then 5 minutes of teacher questions.", "A global issue must be significant at scale, transnational, and visible in everyday local contexts.", "Works used for the individual oral may NOT be reused for the HL essay or for paper 2.", "Four criteria A-D at 10 marks each, total 40.", "The three syllabus headings are areas of exploration shared by SL and HL, not a prescribed reading list; the briefs do not identify the works selected by a school.", "Objectives 1–3 are paraphrased from matching 2021 IB briefs hosted independently by two schools. The communication bullet expressly limited to literature and performance is excluded because this record is a different course. The briefs give assessment-component percentages, not per-objective weights; objective weightings remain null."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_LANG_B",
            qualification: .ibDP,
            board: nil,
            subject: "Language B",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Get your message across clearly, adjusting how you communicate to the setting and what you want to achieve.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Recognise the language a situation and audience call for, and choose expressions that fit personal exchanges and communication across cultures.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Express your ideas and respond to other people’s ideas with accurate language and a smooth flow.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Select the ideas you need for a topic, arrange them coherently and present them to your audience.", weightingMin: nil, weightingMax: nil),         .init(code: "AO5", name: "Work out what written, spoken, visual and combined sound-and-image texts convey; examine their choices and reflect on what you understand.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Individual oral (SL)", kind: .internalAssessment, minutes: 15, marks: 30, weighting: 25, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Language", marks: 12, guidance: "Accuracy and fluency: grammar, vocabulary, pronunciation and coherence across the whole oral."), .init(code: "B", name: "Message", marks: 12, guidance: "Ideas that actually engage the stimulus or extract, developed rather than listed."), .init(code: "C", name: "Interactive skills: communication", marks: 6, guidance: "Move the conversation forward yourself. Answering only what you are asked caps this.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 75, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Individual oral (HL)", kind: .internalAssessment, minutes: 15, marks: 30, weighting: 25, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Language", marks: 12, guidance: "Accuracy and fluency: grammar, vocabulary, pronunciation and coherence across the whole oral."), .init(code: "B", name: "Message", marks: 12, guidance: "Ideas that actually engage the stimulus or extract, developed rather than listed."), .init(code: "C", name: "Interactive skills: communication", marks: 6, guidance: "Move the conversation forward yourself. Answering only what you are asked caps this.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 75, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["SL: presentation on a visual stimulus tied to a prescribed theme. HL: presentation on an extract from a studied literary work.", "Three criteria: Language 12, Message 12, Interactive skills 6 — total 30.", "On paper 1, ignoring context, purpose and audience can score zero for message and conceptual understanding even with strong language.", "Language acquisition is the exception to IB's general position on spelling and grammar; language-improvement software is not permitted.", "The five prescribed themes apply to both SL and HL. The briefs distinguish these from optional recommended topics, which are not presented here as compulsory syllabus content. The first-assessment-2029 replacement is not used for this 2020 record.", "The five objectives are paraphrased from two independently hosted matching IB briefs; the matching guide confirms their numbering. Neither brief publishes per-objective weightings, so those ranges remain null.", "Both matching first-assessment-2020 briefs explicitly give the same assessment split at SL and HL: external 75% and individual oral 25% (p. 2 assessment table; https://www.didzdvaris.lt/wp-content/uploads/2020/12/lang-b-2018-en.pdf and https://www.purcellmarian.org/wp-content/uploads/2024/09/lang-b-2018-en.pdf). HL changes the task demands, not these component percentages."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
        .init(
            code: "IB_DP_MATHS_AA",
            qualification: .ibDP,
            board: nil,
            subject: "Mathematics: analysis and approaches",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Choose and use the mathematical facts and methods you need, including in unfamiliar settings.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Solve abstract and practical problems with suitable mathematical models, results and techniques.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Turn a situation into mathematics, explain what your result means, and present your working with clear diagrams and notation.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Use suitable technology accurately to investigate ideas and solve problems.", weightingMin: nil, weightingMax: nil),         .init(code: "AO5", name: "Justify your conclusions through precise statements, logical steps and algebraic reasoning.", weightingMin: nil, weightingMax: nil),         .init(code: "AO6", name: "Investigate unfamiliar problems: organize evidence, propose a conjecture, test it and assess your conclusion.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Mathematical exploration (SL)", kind: .internalAssessment, minutes: 750, marks: 20, weighting: 20, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Presentation", marks: 4, guidance: "How the exploration is organised and whether it coheres."), .init(code: "B", name: "Mathematical communication", marks: 4, guidance: "Whether the notation, terminology and representation suit the mathematics."), .init(code: "C", name: "Personal engagement", marks: 3, guidance: "Evidence of engaging with the mathematics itself, not enthusiasm for the topic."), .init(code: "D", name: "Reflection", marks: 3, guidance: "Reviewing and evaluating the exploration, not describing what was done."), .init(code: "E", name: "Use of mathematics", marks: 6, guidance: "Mathematics at the right level, correct, and visibly understood.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Mathematical exploration (HL)", kind: .internalAssessment, minutes: 750, marks: 20, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Presentation", marks: 4, guidance: "How the exploration is organised and whether it coheres."), .init(code: "B", name: "Mathematical communication", marks: 4, guidance: "Whether the notation, terminology and representation suit the mathematics."), .init(code: "C", name: "Personal engagement", marks: 3, guidance: "Evidence of engaging with the mathematics itself, not enthusiasm for the topic."), .init(code: "D", name: "Reflection", marks: 3, guidance: "Reviewing and evaluating the exploration, not describing what was done."), .init(code: "E", name: "Use of mathematics", marks: 6, guidance: "Mathematics at the right level, correct, and visibly understood.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["No word limit; 12 to 20 pages recommended.", "HL expects greater sophistication and rigour in Use of mathematics.", "Cite at the point of use; a bibliography alone can become a misconduct finding.", "Figures taken from the Albus IB knowledge base v1.0 (compiled August 2026), which paraphrases the official IB subject guides rather than reproducing them. Verify against the current guide before quoting marks to a student.", "The two independently hosted IB briefs agree on five syllabus topic headings and six subject-wide objectives, common to AA and AI at SL and HL. These are the 2021 courses, not the separately published 2029 replacements. The exploration is an assessment activity, not a sixth topic.", "Objective descriptions are Albus’s own second-person paraphrases. The matching AA guide numbers the common objectives 1–6; the briefs explicitly confirm the same objectives for AI. Per-paper ranges in that guide are not whole-subject weights, so weightingMin/Max remain null. Numbering cross-check: https://www.cygnusinternational.org/uploads/pdf/HIW0a2e9G5GwAkAecvc1GoP3TfPesY9oKvaot4gC.pdf (retrieved 2026-09-09; First assessment 2021, printed pages 23–24)."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-08-25"
        ),
        .init(
            code: "IB_DP_MATHS_AI",
            qualification: .ibDP,
            board: nil,
            subject: "Mathematics: applications and interpretation",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Choose and use the mathematical facts and methods you need, including in unfamiliar settings.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Solve abstract and practical problems with suitable mathematical models, results and techniques.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Turn a situation into mathematics, explain what your result means, and present your working with clear diagrams and notation.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Use suitable technology accurately to investigate ideas and solve problems.", weightingMin: nil, weightingMax: nil),         .init(code: "AO5", name: "Justify your conclusions through precise statements, logical steps and algebraic reasoning.", weightingMin: nil, weightingMax: nil),         .init(code: "AO6", name: "Investigate unfamiliar problems: organize evidence, propose a conjecture, test it and assess your conclusion.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Mathematical exploration (SL)", kind: .internalAssessment, minutes: 750, marks: 20, weighting: 20, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Presentation", marks: 4, guidance: "How the exploration is organised and whether it coheres."), .init(code: "B", name: "Mathematical communication", marks: 4, guidance: "Whether the notation, terminology and representation suit the mathematics."), .init(code: "C", name: "Personal engagement", marks: 3, guidance: "Evidence of engaging with the mathematics itself, not enthusiasm for the topic."), .init(code: "D", name: "Reflection", marks: 3, guidance: "Reviewing and evaluating the exploration, not describing what was done."), .init(code: "E", name: "Use of mathematics", marks: 6, guidance: "Mathematics at the right level, correct, and visibly understood.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Mathematical exploration (HL)", kind: .internalAssessment, minutes: 750, marks: 20, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Presentation", marks: 4, guidance: "How the exploration is organised and whether it coheres."), .init(code: "B", name: "Mathematical communication", marks: 4, guidance: "Whether the notation, terminology and representation suit the mathematics."), .init(code: "C", name: "Personal engagement", marks: 3, guidance: "Evidence of engaging with the mathematics itself, not enthusiasm for the topic."), .init(code: "D", name: "Reflection", marks: 3, guidance: "Reviewing and evaluating the exploration, not describing what was done."), .init(code: "E", name: "Use of mathematics", marks: 6, guidance: "Mathematics at the right level, correct, and visibly understood.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["No word limit; 12 to 20 pages recommended.", "HL expects greater sophistication and rigour in Use of mathematics.", "Figures taken from the Albus IB knowledge base v1.0 (compiled August 2026), which paraphrases the official IB subject guides rather than reproducing them. Verify against the current guide before quoting marks to a student.", "The two independently hosted IB briefs agree on five syllabus topic headings and six subject-wide objectives, common to AA and AI at SL and HL. These are the 2021 courses, not the separately published 2029 replacements. The exploration is an assessment activity, not a sixth topic.", "Objective descriptions are Albus’s own second-person paraphrases. The matching AA guide numbers the common objectives 1–6; the briefs explicitly confirm the same objectives for AI. Per-paper ranges in that guide are not whole-subject weights, so weightingMin/Max remain null. Numbering cross-check: https://www.cygnusinternational.org/uploads/pdf/HIW0a2e9G5GwAkAecvc1GoP3TfPesY9oKvaot4gC.pdf (retrieved 2026-09-09; First assessment 2021, printed pages 23–24)."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-08-25"
        ),
        .init(
            code: "IB_DP_PHYSICS",
            qualification: .ibDP,
            board: nil,
            subject: "Physics",
            specCode: nil,
            objectives: [
        .init(code: "AO1", name: "Show that you know the subject’s facts, vocabulary and ideas, as well as its practical skills and methods.", weightingMin: nil, weightingMax: nil),         .init(code: "AO2", name: "Use your understanding of the subject’s ideas and vocabulary to choose and apply suitable skills and methods.", weightingMin: nil, weightingMax: nil),         .init(code: "AO3", name: "Examine experimental methods and data you collect or obtain from other sources; judge their quality and bring the evidence together to explain patterns and make predictions.", weightingMin: nil, weightingMax: nil),         .init(code: "AO4", name: "Use your practical and analytical skills to investigate a worthwhile question, making responsible ethical choices throughout.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "IA_SL", name: "Scientific investigation (SL)", kind: .internalAssessment, minutes: 600, marks: 24, weighting: 20, level: "SL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research design", marks: 6, guidance: "State the question with its variables and enough method to repeat."), .init(code: "B", name: "Data analysis", marks: 6, guidance: "Record, process and present data so a conclusion can be drawn, uncertainties included."), .init(code: "C", name: "Conclusion", marks: 6, guidance: "Answer your own question against the analysis and published science, uncertainties included."), .init(code: "D", name: "Evaluation", marks: 6, guidance: "Name the specific weaknesses that mattered most and improvements that address them.")]),
            .init(code: "EXTERNAL_SL", name: "Examinations (SL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "SL", covers: nil, format: nil, criteria: []),
            .init(code: "IA_HL", name: "Scientific investigation (HL)", kind: .internalAssessment, minutes: 600, marks: 24, weighting: 20, level: "HL", covers: nil, format: nil, criteria: [.init(code: "A", name: "Research design", marks: 6, guidance: "State the question with its variables and enough method to repeat."), .init(code: "B", name: "Data analysis", marks: 6, guidance: "Record, process and present data so a conclusion can be drawn, uncertainties included."), .init(code: "C", name: "Conclusion", marks: 6, guidance: "Answer your own question against the analysis and published science, uncertainties included."), .init(code: "D", name: "Evaluation", marks: 6, guidance: "Name the specific weaknesses that mattered most and improvements that address them.")]),
            .init(code: "EXTERNAL_HL", name: "Examinations (HL)", kind: .exam, minutes: nil, marks: nil, weighting: 80, level: "HL", covers: nil, format: nil, criteria: [])
            ],
            notes: ["Identical IA across Biology, Chemistry and Physics under the first-assessment-2025 guides.", "Report maximum 3,000 words; tables, calculations, citations, graphs and appendices are excluded.", "Conclusion and Evaluation are together half the marks.", "Figures taken from the Albus IB knowledge base v1.0 (compiled August 2026), which paraphrases the official IB subject guides rather than reproducing them. Verify against the current guide before quoting marks to a student.", "Topic labels were read from the official page’s physics-sylabus-content-overview-en.png. HL-only labels retain that restriction; shared topics may include additional HL content. First teaching 2023 matches the first-assessment-2025 specification.", "AO1–AO4 are Albus’s own second-person paraphrases of the matching 2025 assessment objectives, checked in two independently hosted IB publications. The brief gives component weightings, not separate per-AO percentages, so objective weights remain null. These are subject-wide objectives; AO4 concerns investigation skills, not a claim that every exam paper separately assesses them."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-08-25"
        ),
        .init(
            code: "IB_DP_TOK",
            qualification: .ibDP,
            board: nil,
            subject: "Theory of knowledge",
            specCode: nil,
            objectives: [
        .init(code: "Albus 1", name: "Examine questions about knowledge critically to show how you think about knowing.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 2", name: "Connect questions about knowledge with situations in the world around you.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 3", name: "Explore how questions about knowledge connect with different areas of knowledge.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 4", name: "Build arguments that stay relevant, make your reasoning clear and hold together.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 5", name: "Support your discussion with examples and evidence that advance your argument.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 6", name: "Consider different viewpoints and assess their strengths and limitations.", weightingMin: nil, weightingMax: nil),         .init(code: "Albus 7", name: "Work through what your arguments and conclusions imply.", weightingMin: nil, weightingMax: nil)
            ],
            components: [
            .init(code: "ESSAY", name: "TOK essay", kind: .coursework, minutes: 1200, marks: 10, weighting: 66.67, level: nil, covers: nil, format: "1,600 words on a prescribed title, externally assessed; counted twice in the aggregate", criteria: [.init(code: "GLOBAL", name: "Clear, coherent and critical exploration of the title", marks: 10, guidance: "Argue about how knowledge is made, not about the topic. Specific, named, dated examples beat general ones.")]),
            .init(code: "EXHIBITION", name: "TOK exhibition", kind: .internalAssessment, minutes: 900, marks: 10, weighting: 33.33, level: nil, covers: nil, format: "950 words on three objects, internally assessed and externally moderated", criteria: [.init(code: "GLOBAL", name: "How TOK manifests in the world around us", marks: 10, guidance: "Three specific objects, each with its own real-world context, each tied explicitly to the prompt.")])
            ],
            notes: ["Both tasks are assessed against a SINGLE global instrument with five holistic levels — not lettered criteria. Modelled as one criterion each on purpose.", "Essay 1,600 words, exhibition 950; examiners stop reading at the limit.", "An exhibition not based on one of the 35 prescribed prompts scores zero.", "The essay counts twice in the aggregate, so it is worth exactly twice the exhibition.", "An E in TOK is a failing condition for the diploma regardless of total points.", "The first-assessment-2022 IB subject brief hosted by Palm Beach County and Heidelberg International School’s 2026-28 handbook agree on the full TOK outline and seven assessment objectives. The objectives are unnumbered in both sources: “Albus 1” through “Albus 7” are local identifiers preserving their order, not official IB AO codes. No separate objective weightings are published. The optional themes are a choice of two, while all five areas of knowledge are required; the outline does not identify the school’s two choices."],
            source: "https://www.ibo.org/programmes/diploma-programme/curriculum/",
            retrievedAt: "2026-09-04"
        ),
    ]

    /// Subjects for one qualification, and — for A-level — one board, since the
    /// same subject is assessed differently by different boards.
    static func subjects(qualification: Qualification, board: String? = nil) -> [CurriculumSubject] {
        all.filter {
            $0.qualification == qualification && (board == nil || $0.board == board)
        }
        .sorted { $0.subject < $1.subject }
    }

    /// Boards offering a qualification, for the onboarding picker.
    static func boards(for qualification: Qualification) -> [String] {
        Set(all.filter { $0.qualification == qualification }.compactMap(\.board))
            .sorted()
    }

    static func find(code: String) -> CurriculumSubject? {
        all.first { $0.code == code }
    }
}
