# Catalogue of study tools. Each: name, host, category, SF Symbol, tint, one-line why.
# Kept as data so the Swift file is generated, not hand-maintained.
T = [
 # ── AI assistants ─────────────────────────────────────────────────────
 ("Claude","claude.ai","ai","sparkles","violet","Think a problem through out loud"),
 ("ChatGPT","chat.openai.com","ai","bubble.left.and.text.bubble.right","green","Explains, drafts, and argues back"),
 ("Perplexity Pro","perplexity.ai","ai","sparkle.magnifyingglass","teal","Answers that cite their sources"),
 ("NotebookLM","notebooklm.google.com","ai","book.and.wrench","blue","Asks questions of your own notes"),
 ("Gemini","gemini.google.com","ai","diamond","blue","Google's assistant, in your docs"),
 ("Consensus","consensus.app","ai","checkmark.message","teal","What the papers actually conclude"),
 ("Elicit","elicit.com","ai","tray.2","violet","Literature review, automated"),
 ("Scite","scite.ai","ai","quote.bubble.fill","orange","Shows who disputes a citation"),

 # ── Writing & language ────────────────────────────────────────────────
 ("Grammarly","grammarly.com","writing","checkmark.bubble","green","Grammar and clarity checks"),
 ("Hemingway Editor","hemingwayapp.com","writing","scissors","amber","Cuts sentences down to size"),
 ("ProWritingAid","prowritingaid.com","writing","text.magnifyingglass","violet","Style report on a long draft"),
 ("LanguageTool","languagetool.org","writing","abc","blue","Grammar in 25+ languages"),
 ("Quillbot","quillbot.com","writing","arrow.2.squarepath","teal","Rephrase a sentence you're stuck on"),
 ("Thesaurus.com","thesaurus.com","writing","book.closed","orange","The word on the tip of your tongue"),
 ("Merriam-Webster","merriam-webster.com","writing","character.book.closed","red","Definitions with real citations"),
 ("Oxford Learner's","oxfordlearnersdictionaries.com","writing","text.book.closed","blue","Definitions built for learners"),
 ("Purdue OWL","owl.purdue.edu","writing","graduationcap","slate","The citation rules, explained"),
 ("Hemingway Mode","typewritermode.com","writing","keyboard","neutral","No backspace. Just write"),
 ("Notion","notion.so","writing","square.stack.3d.up","neutral","Notes, docs and databases in one"),
 ("Obsidian","obsidian.md","writing","link","violet","Notes that link to each other"),
 ("Google Docs","docs.google.com","writing","doc.text","blue","Write and share in the browser"),
 ("Overleaf","overleaf.com","writing","function","green","LaTeX without installing LaTeX"),
 ("Scrivener","literatureandlatte.com","writing","doc.on.doc","amber","For work too long for one document"),
 ("Ulysses","ulysses.app","writing","pencil.and.outline","violet","Distraction-free long-form writing"),
 ("Zotero","zotero.org","writing","books.vertical","red","Collects sources and formats them"),
 ("Mendeley","mendeley.com","writing","doc.badge.plus","red","Reference manager with a PDF reader"),
 ("EndNote","endnote.com","writing","list.bullet.rectangle","slate","Reference manager universities use"),
 ("Citation Machine","citationmachine.net","writing","quote.opening","orange","One citation, formatted fast"),
 ("ZoteroBib","zbib.org","writing","quote.bubble","red","A bibliography with no account"),
 ("Scribbr","scribbr.com","writing","checkmark.seal","green","Citation guides and a plagiarism check"),
 ("Hemingway Grade","readabilityformulas.com","writing","gauge.medium","amber","How hard your writing is to read"),
 ("WordCounter","wordcounter.net","writing","number","neutral","Words, characters, reading time"),
 ("OneLook","onelook.com","writing","magnifyingglass","blue","Find the word from its meaning"),

 # ── Research & sources ────────────────────────────────────────────────
 ("Google Scholar","scholar.google.com","research","graduationcap.circle","blue","Scholarly articles and citations"),
 ("JSTOR","jstor.org","research","building.columns","neutral","Journals and primary sources"),
 ("PubMed","pubmed.ncbi.nlm.nih.gov","research","cross.case","teal","Biomedical and life-science papers"),
 ("arXiv","arxiv.org","research","doc.plaintext","red","Preprints in physics, maths, CS"),
 ("Semantic Scholar","semanticscholar.org","research","brain","violet","Finds the papers that matter"),
 ("Connected Papers","connectedpapers.com","research","point.3.connected.trianglepath.dotted","teal","A map of a field from one paper"),
 ("ResearchGate","researchgate.net","research","person.2","teal","Papers straight from the authors"),
 ("CORE","core.ac.uk","research","square.grid.3x3","slate","Open-access papers, all of them"),
 ("DOAJ","doaj.org","research","lock.open","green","Directory of open-access journals"),
 ("Sci-Hub Alternatives","openaccessbutton.org","research","key","amber","Legal routes to a paywalled paper"),
 ("Unpaywall","unpaywall.org","research","lock.open.rotation","green","Finds the free version of a paper"),
 ("Internet Archive","archive.org","research","clock.arrow.circlepath","slate","Books, pages and media, preserved"),
 ("Project Gutenberg","gutenberg.org","research","book","amber","Sixty thousand free books"),
 ("Perplexity","perplexity.ai","research","sparkle.magnifyingglass","teal","Answers that cite their sources"),
 ("Wikipedia","wikipedia.org","research","globe","neutral","Start here, then follow the footnotes"),
 ("Britannica","britannica.com","research","building.columns.circle","blue","Encyclopaedia you can cite"),
 ("Our World in Data","ourworldindata.org","research","chart.xyaxis.line","teal","Charts you can actually cite"),
 ("Statista","statista.com","research","chart.bar.doc.horizontal","blue","Statistics with sources attached"),
 ("World Bank Data","data.worldbank.org","research","globe.americas","green","Country-level economic data"),
 ("UN Data","data.un.org","research","globe.europe.africa","blue","Official international statistics"),
 ("Eurostat","ec.europa.eu","research","flag","blue","European statistics"),
 ("Google Dataset Search","datasetsearch.research.google.com","research","tablecells","blue","Finds datasets across the web"),
 ("Library Genesis Info","openlibrary.org","research","books.vertical.circle","amber","Open Library's lending catalogue"),
 ("HathiTrust","hathitrust.org","research","text.book.closed.fill","slate","Digitised academic library"),
 ("JSTOR Daily","daily.jstor.org","research","newspaper","neutral","Scholarship explained readably"),
 ("Nature","nature.com","research","leaf","green","The journal, and its news"),
 ("Science","science.org","research","atom","red","AAAS research and commentary"),
 ("SSRN","ssrn.com","research","doc.richtext","slate","Social-science preprints"),
 ("PhilPapers","philpapers.org","research","bubble.left.and.bubble.right","violet","Philosophy index and archive"),
 ("Historical Atlas","worldhistory.org","research","map","amber","World history encyclopaedia"),

 # ── Maths & problem solving ───────────────────────────────────────────
 ("Wolfram Alpha","wolframalpha.com","math","function","red","Computational answers, step by step"),
 ("Symbolab","symbolab.com","math","x.squareroot","orange","Solves and shows the working"),
 ("Desmos","desmos.com","math","chart.dots.scatter","green","Graphing that makes it obvious"),
 ("GeoGebra","geogebra.org","math","triangle","blue","Geometry, algebra and calculus"),
 ("Photomath","photomath.com","math","camera.viewfinder","red","Point at the problem, see the steps"),
 ("Mathway","mathway.com","math","equal.square","blue","Step-by-step across every branch"),
 ("Khan Academy","khanacademy.org","math","play.rectangle","green","Free lessons and practice"),
 ("Brilliant","brilliant.org","math","lightbulb","amber","Maths by solving, not watching"),
 ("Paul's Notes","tutorial.math.lamar.edu","math","doc.text.below.ecg","slate","Calculus notes that actually explain"),
 ("3Blue1Brown","3blue1brown.com","math","eye","blue","The intuition behind the formula"),
 ("Integral Calculator","integral-calculator.com","math","sum","orange","Integrals with the steps shown"),
 ("Derivative Calculator","derivative-calculator.net","math","angle","orange","Derivatives with the steps shown"),
 ("Matrix Calculator","matrixcalc.org","math","square.grid.3x3.fill","slate","Linear algebra, worked through"),
 ("Statistics Kingdom","statskingdom.com","math","chart.bar","teal","Runs the test and reads the result"),
 ("Desmos Matrix","desmos.com","math","squareshape.split.2x2","green","Matrices you can see"),
 ("SageMath","sagemath.org","math","terminal","green","Open-source computer algebra"),
 ("Numbas","numbas.mathcentre.ac.uk","math","checklist","blue","Practice questions that mark themselves"),
 ("Project Euler","projecteuler.net","math","number.square","slate","Maths problems worth the struggle"),
 ("OEIS","oeis.org","math","list.number","neutral","Identify any integer sequence"),
 ("Mathigon","mathigon.org","math","puzzlepiece","violet","Textbook that talks back"),

 # ── Science ───────────────────────────────────────────────────────────
 ("PhET Simulations","phet.colorado.edu","science","atom","amber","Run the experiment in a browser"),
 ("ChemSpider","chemspider.com","science","testtube.2","teal","Chemical structures and properties"),
 ("PubChem","pubchem.ncbi.nlm.nih.gov","science","flask","blue","The chemistry database"),
 ("Periodic Table","ptable.com","science","tablecells.badge.ellipsis","orange","Interactive, and actually useful"),
 ("BioRender","biorender.com","science","waveform.path.ecg","teal","Diagrams that look publishable"),
 ("Protein Data Bank","rcsb.org","science","circles.hexagongrid","violet","3D structures of proteins"),
 ("NASA Earthdata","earthdata.nasa.gov","science","globe.badge.chevron.backward","blue","Satellite and climate data"),
 ("Stellarium Web","stellarium-web.org","science","moon.stars","slate","The sky from anywhere, any date"),
 ("Physics Classroom","physicsclassroom.com","science","bolt","amber","Mechanics explained slowly"),
 ("HyperPhysics","hyperphysics.gsu.edu","science","link.circle","blue","Physics as a concept map"),
 ("Anatomy Atlas","innerbody.com","science","figure.stand","red","Human anatomy, layer by layer"),
 ("Genetics Home Ref","medlineplus.gov","science","allergens","teal","Genetics for non-specialists"),
 ("Climate Data","climate.gov","science","thermometer.medium","orange","Climate records and explainers"),
 ("USGS","usgs.gov","science","mountain.2","green","Geology, water and hazards"),
 ("Encyclopedia of Life","eol.org","science","tortoise","green","Every known species"),
 ("Foldit","fold.it","science","hand.raised","violet","Protein folding as a puzzle"),
 ("Labster","labster.com","science","flask.fill","blue","Virtual lab work"),
 ("Concord Consortium","learn.concord.org","science","atom","teal","Free science simulations"),

 # ── Coding ────────────────────────────────────────────────────────────
 ("GitHub","github.com","coding","chevron.left.forwardslash.chevron.right","slate","Code hosting and history"),
 ("Replit","replit.com","coding","play.square","blue","Write and run code in the browser"),
 ("Stack Overflow","stackoverflow.com","coding","questionmark.bubble","orange","Someone has hit this before"),
 ("MDN Web Docs","developer.mozilla.org","coding","doc.append","blue","The web platform reference"),
 ("W3Schools","w3schools.com","coding","tag","green","Quick syntax, quick examples"),
 ("LeetCode","leetcode.com","coding","brain.head.profile","amber","Interview-style problem practice"),
 ("HackerRank","hackerrank.com","coding","terminal.fill","green","Practice with automated marking"),
 ("Codecademy","codecademy.com","coding","laptopcomputer","violet","Learn by typing, not watching"),
 ("freeCodeCamp","freecodecamp.org","coding","flame","neutral","Full curriculum, genuinely free"),
 ("Exercism","exercism.org","coding","dumbbell","teal","Small exercises, human feedback"),
 ("Regex101","regex101.com","coding","textformat.abc.dottedunderline","blue","Explains your regex back to you"),
 ("JSON Formatter","jsonformatter.org","coding","curlybraces","orange","Makes unreadable JSON readable"),
 ("Compiler Explorer","godbolt.org","coding","cpu","red","See what your code compiles to"),
 ("DevDocs","devdocs.io","coding","books.vertical.fill","slate","Every API doc, one search box"),
 ("CodePen","codepen.io","coding","square.on.square","neutral","Front-end sketching"),
 ("Jupyter","jupyter.org","coding","book.and.wrench","orange","Notebooks for data work"),
 ("Google Colab","colab.research.google.com","coding","cloud","amber","Notebooks with a free GPU"),
 ("Kaggle","kaggle.com","coding","chart.bar.xaxis","blue","Datasets and data-science practice"),
 ("Python Docs","docs.python.org","coding","chevron.left.slash.chevron.right","blue","The language reference"),
 ("Swift Docs","swift.org","coding","swift","orange","The Swift language guide"),
 ("Visual Studio Code","code.visualstudio.com","coding","square.and.pencil","blue","The editor most people use"),
 ("Git Docs","git-scm.com","coding","arrow.triangle.branch","red","What that git command does"),

 # ── Languages ─────────────────────────────────────────────────────────
 ("DeepL","deepl.com","languages","character.bubble","blue","Translation that reads naturally"),
 ("Linguee","linguee.com","languages","text.quote","green","Translations in real sentences"),
 ("Google Translate","translate.google.com","languages","globe.badge.chevron.backward","blue","Fast, everywhere, every language"),
 ("WordReference","wordreference.com","languages","character.book.closed.fill","orange","Dictionary plus forum arguments"),
 ("Duolingo","duolingo.com","languages","bird","green","Fifteen minutes a day"),
 ("Anki","apps.ankiweb.net","languages","rectangle.stack","blue","Spaced repetition that works"),
 ("Memrise","memrise.com","languages","brain.filled.head.profile","teal","Vocabulary from real speakers"),
 ("Conjuguemos","conjuguemos.com","languages","arrow.trianglehead.2.clockwise","violet","Verb conjugation drills"),
 ("Reverso Context","context.reverso.net","languages","text.alignleft","blue","How the phrase is actually used"),
 ("Forvo","forvo.com","languages","speaker.wave.2","orange","Hear a native say the word"),
 ("Tatoeba","tatoeba.org","languages","text.bubble","teal","Example sentences, many languages"),
 ("Lang-8 / HiNative","hinative.com","languages","person.wave.2","green","Ask a native speaker"),
 ("Clozemaster","clozemaster.com","languages","square.dashed","violet","Vocabulary in context, gamified"),
 ("Readlang","readlang.com","languages","doc.text.magnifyingglass","amber","Read real pages with a click-dictionary"),

 # ── Focus & study method ──────────────────────────────────────────────
 ("Forest","forestapp.cc","focus","tree","green","Grow a tree by not touching your phone"),
 ("Pomofocus","pomofocus.io","focus","timer","red","A clean pomodoro timer"),
 ("Toggl Track","toggl.com","focus","stopwatch","violet","Where the hours actually went"),
 ("Cold Turkey","getcoldturkey.com","focus","hand.raised.slash","slate","Blocks sites properly"),
 ("Freedom","freedom.to","focus","lock.shield","blue","Blocks across all your devices"),
 ("Noisli","noisli.com","focus","waveform","teal","Background noise that helps"),
 ("Brain.fm","brain.fm","focus","headphones","violet","Music built for concentration"),
 ("Rainy Mood","rainymood.com","focus","cloud.rain","blue","Rain, and nothing else"),
 ("Lofi Girl","lofigirl.com","focus","music.note","orange","The one everybody uses"),
 ("Focusmate","focusmate.com","focus","person.2.wave.2","teal","A stranger works alongside you"),
 ("Study Together","studytogether.com","focus","rectangle.3.group","violet","Virtual library rooms"),
 ("Habitica","habitica.com","focus","gamecontroller","violet","Habits as a role-playing game"),
 ("Streaks","streaksapp.com","focus","flame.fill","orange","Keep the chain unbroken"),
 ("Sleep Cycle","sleepcycle.com","focus","bed.double","blue","Because sleep is study time"),

 # ── Notes, memory & organisation ──────────────────────────────────────
 ("Quizlet","quizlet.com","memory","rectangle.on.rectangle","blue","Flashcards, and everyone else's"),
 ("Anki Web","ankiweb.net","memory","rectangle.stack.fill","blue","Your Anki deck in a browser"),
 ("RemNote","remnote.com","memory","note.text","violet","Notes that become flashcards"),
 ("Brainscape","brainscape.com","memory","square.stack","teal","Confidence-based repetition"),
 ("Cram","cram.com","memory","rectangle.split.3x1","orange","Flashcards without an account"),
 ("Knowt","knowt.com","memory","doc.text.fill","green","Turns your notes into a quiz"),
 ("GoodNotes","goodnotes.com","memory","hand.draw","green","Handwriting that stays searchable"),
 ("Notability","notability.com","memory","pencil.tip","amber","Notes with the lecture recorded"),
 ("OneNote","onenote.com","memory","note","violet","Free, and syncs everywhere"),
 ("Evernote","evernote.com","memory","square.and.pencil.circle","green","The original notes app"),
 ("Milanote","milanote.com","memory","square.grid.2x2","neutral","Notes on a board, not a list"),
 ("Miro","miro.com","memory","rectangle.dashed","amber","A whiteboard big enough"),
 ("Excalidraw","excalidraw.com","memory","scribble","violet","Diagrams that look hand-drawn"),
 ("Whimsical","whimsical.com","memory","flowchart","teal","Flowcharts and mind maps"),
 ("XMind","xmind.app","memory","point.topleft.down.to.point.bottomright.curvepath","orange","Mind maps that stay tidy"),
 ("Coggle","coggle.it","memory","circle.hexagongrid","green","Shared mind maps"),
 ("Todoist","todoist.com","memory","checklist.checked","red","The list that actually gets used"),
 ("TickTick","ticktick.com","memory","checkmark.circle","blue","Tasks with a pomodoro built in"),
 ("Google Calendar","calendar.google.com","memory","calendar","blue","Where your real week lives"),
 ("Trello","trello.com","memory","square.grid.3x1.below.line.grid.1x2","blue","Boards for a group project"),

 # ── Presenting & design ───────────────────────────────────────────────
 ("Canva","canva.com","presenting","paintpalette","teal","Design without being a designer"),
 ("Google Slides","slides.google.com","presenting","rectangle.on.rectangle.angled","amber","Slides you can share instantly"),
 ("Beautiful.ai","beautiful.ai","presenting","wand.and.stars","violet","Slides that lay themselves out"),
 ("Prezi","prezi.com","presenting","arrow.up.left.and.down.right.magnifyingglass","blue","When a straight line won't do"),
 ("Pitch","pitch.com","presenting","play.rectangle.on.rectangle","slate","Decks built with other people"),
 ("Unsplash","unsplash.com","presenting","photo","neutral","Free photographs worth using"),
 ("Pexels","pexels.com","presenting","photo.stack","teal","Free photos and video"),
 ("The Noun Project","thenounproject.com","presenting","square.on.circle","slate","An icon for anything"),
 ("Flaticon","flaticon.com","presenting","star.square","blue","Icons, many formats"),
 ("Coolors","coolors.co","presenting","swatchpalette","orange","A palette in three seconds"),
 ("Google Fonts","fonts.google.com","presenting","textformat","blue","Free type that loads fast"),
 ("Remove.bg","remove.bg","presenting","person.crop.rectangle","green","Cuts out the background"),
 ("Figma","figma.com","presenting","pencil.and.ruler","violet","Design, together, in a browser"),
 ("Loom","loom.com","presenting","record.circle","violet","Record the walkthrough instead"),
 ("OBS Studio","obsproject.com","presenting","video","slate","Record or stream your screen"),
 ("Descript","descript.com","presenting","waveform.badge.mic","blue","Edit audio by editing text"),
 ("Audacity","audacityteam.org","presenting","waveform.circle","orange","Free audio editing"),
 ("DaVinci Resolve","blackmagicdesign.com","presenting","film","slate","Professional video, free tier"),
 ("Datawrapper","datawrapper.de","presenting","chart.pie","teal","Charts that explain themselves"),
 ("Flourish","flourish.studio","presenting","chart.line.uptrend.xyaxis.circle","violet","Animated data storytelling"),

 # ── Exams & subject revision ──────────────────────────────────────────
 ("Save My Exams","savemyexams.com","revision","doc.badge.gearshape","violet","Revision notes by exam board"),
 ("Physics & Maths Tutor","physicsandmathstutor.com","revision","tray.full","blue","Past papers, sorted by topic"),
 ("Revision World","revisionworld.com","revision","book.pages","green","Notes across GCSE and A-level"),
 ("Seneca Learning","senecalearning.com","revision","brain.head.profile.fill","violet","Revision that adapts to you"),
 ("BBC Bitesize","bbc.co.uk","revision","tv","red","Short, clear, and free"),
 ("CrashCourse","thecrashcourse.com","revision","play.tv","amber","A subject in ten-minute pieces"),
 ("Khan Academy SAT","khanacademy.org","revision","pencil.circle","green","Official SAT practice"),
 ("College Board","collegeboard.org","revision","building.columns.fill","blue","AP and SAT, from the source"),
 ("IB Documents","ibo.org","revision","doc.zipper","slate","The official IB subject guides"),
 ("Quizizz","quizizz.com","revision","gamecontroller.fill","violet","Revision as a class game"),
 ("Kahoot","kahoot.com","revision","flag.checkered","violet","The one everyone shouts at"),
 ("Wooclap","wooclap.com","revision","hand.thumbsup","blue","Live questions in a lecture"),
 ("Socratic","socratic.org","revision","camera.metering.center.weighted","teal","Photograph the question"),
 ("Chegg Study","chegg.com","revision","book.circle","orange","Worked textbook solutions"),
 ("Course Hero","coursehero.com","revision","doc.on.clipboard","green","Course notes from other students"),
 ("Studocu","studocu.com","revision","doc.text.image","blue","Shared summaries and past papers"),
 ("SparkNotes","sparknotes.com","revision","book.closed.fill","amber","The novel, and what it means"),
 ("LitCharts","litcharts.com","revision","text.book.closed","teal","Literature analysis, colour-coded"),
 ("Shmoop","shmoop.com","revision","face.smiling","orange","Literature with a sense of humour"),
 ("Marked by Teachers","markedbyteachers.com","revision","checkmark.rectangle.stack","slate","Real essays with real marks"),

 # ── Wellbeing & the rest of it ────────────────────────────────────────
 ("Headspace","headspace.com","wellbeing","figure.mind.and.body","orange","Ten minutes before you start"),
 ("Calm","calm.com","wellbeing","moon.zzz","blue","For the night before"),
 ("Insight Timer","insighttimer.com","wellbeing","timer.circle","teal","Free guided meditation"),
 ("Finch","finchcare.com","wellbeing","bird.fill","teal","Self-care that doesn't feel like it"),
 ("Daylio","daylio.net","wellbeing","face.dashed","violet","Mood in two taps a day"),
 ("Stretchly","hovancik.net","wellbeing","figure.flexibility","green","Reminds you to look away"),
 ("f.lux","justgetflux.com","wellbeing","sun.horizon","orange","Screen warmth after dark"),
 ("Water Reminder","waterllama.app","wellbeing","drop","blue","Drink something that isn't coffee"),
 ("Nike Training","nike.com","wellbeing","figure.run","slate","Twenty minutes, no equipment"),
 ("Yoga with Adriene","yogawithadriene.com","wellbeing","figure.yoga","green","Free, and genuinely kind"),
 ("7 Cups","7cups.com","wellbeing","heart.text.square","teal","Someone to talk to, free"),
 ("Student Minds","studentminds.org.uk","wellbeing","hand.raised.fill","violet","Student mental health support"),
 ("Sleepyti.me","sleepyti.me","wellbeing","alarm","blue","When to go to bed, working back"),
 ("MyFitnessPal","myfitnesspal.com","wellbeing","fork.knife","orange","Eating like a person, not a student"),
]

CATS = [("ai","AI help"),("writing","Writing"),("research","Research"),("math","Maths"),("science","Science"),
        ("coding","Coding"),("languages","Languages"),("focus","Focus"),("memory","Notes & memory"),
        ("presenting","Presenting"),("revision","Revision"),("wellbeing","Wellbeing")]

names = [t[0] for t in T]
assert len(names) == len(set(names)), "duplicate tool names: " + str([n for n in names if names.count(n)>1])
cats_used = {t[2] for t in T}
assert cats_used <= {c[0] for c in CATS}, cats_used - {c[0] for c in CATS}
print(f"{len(T)} tools across {len(CATS)} categories")
for key, label in CATS:
    print(f"  {label:16} {sum(1 for t in T if t[2]==key)}")
