-- scripts/curriculum/seed.sql
--
-- Generated by scripts/curriculum/gen.py — do not edit by hand. Edit
-- scripts/curriculum/data/*.json and regenerate, or the file and the database
-- drift and the repo stops describing what is deployed.
--
-- Not a migration, on purpose: migrations are append-only history and this is
-- regenerated whenever a subject is added. Apply with ./apply_seed.sh.
--
-- This is what makes a generated plan curriculum-aware. `breakdown` looks up an
-- assessment type by the id the client sends and grounds the prompt in what that
-- component actually is — how long the paper is, what it is worth, what the
-- assessment objectives reward.
--
-- Read-only reference data: every table here already carries a read-all policy
-- for signed-in users and no write grant, so seeding adds no new attack surface.
--
-- Idempotent by design. It re-runs whenever the corpus grows.

-- Curricula. A-level is split by board because the boards genuinely
-- assess the same subject differently; treating them as one would be wrong.
insert into public.curricula (code, name) values ('A_LEVEL_AQA', 'A-Level (AQA)')
  on conflict (code) do update set name = excluded.name;

-- Subjects, their components, and their assessment objectives.

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_BIOLOGY', 'Biology')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO1', 'Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures', 30, 35, 0);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO2', 'Apply knowledge and understanding of scientific ideas, processes, techniques and procedures', 40, 45, 1);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO3', 'Analyse, interpret and evaluate scientific information, ideas and evidence', 25, 30, 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_CHEMISTRY', 'Chemistry')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO1', 'Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures', 30, 30, 0);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO2', 'Apply knowledge and understanding of scientific ideas, processes, techniques and procedures', 45, 45, 1);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO3', 'Analyse, interpret and evaluate scientific information, ideas and evidence', 25, 25, 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_PHYSICS', 'Physics')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO1', 'Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures', 33, 33, 0);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO2', 'Apply knowledge and understanding of scientific ideas, processes, techniques and procedures', 42, 42, 1);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO3', 'Analyse, interpret and evaluate scientific information, ideas and evidence', 25, 25, 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;
