-- scripts/curriculum/seed.sql
--
-- Generated by scripts/curriculum/gen.py — do not edit by hand. Edit
-- scripts/curriculum/data/*.json and regenerate, or the file and the database
-- drift and the repo stops describing what is deployed.
--
-- Not a migration, on purpose: migrations are append-only history and this is
-- regenerated whenever a subject is added. Apply with ./apply_seed.sh.
--
-- This is what makes a generated plan curriculum-aware. `breakdown` looks up an
-- assessment type by the id the client sends and grounds the prompt in what that
-- component actually is — how long the paper is, what it is worth, what the
-- assessment objectives reward.
--
-- Read-only reference data: every table here already carries a read-all policy
-- for signed-in users and no write grant, so seeding adds no new attack surface.
--
-- Idempotent by design. It re-runs whenever the corpus grows.

-- Curricula. A-level is split by board because the boards genuinely
-- assess the same subject differently; treating them as one would be wrong.
insert into public.curricula (code, name) values ('A_LEVEL_AQA', 'A-Level (AQA)')
  on conflict (code) do update set name = excluded.name;
insert into public.curricula (code, name) values ('IB_DP', 'International Baccalaureate Diploma Programme')
  on conflict (code) do update set name = excluded.name;

-- Subjects, their components, and their assessment objectives.

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_BIOLOGY', 'Biology')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO1', 'Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures', 30, 35, 0);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO2', 'Apply knowledge and understanding of scientific ideas, processes, techniques and procedures', 40, 45, 1);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO3', 'Analyse, interpret and evaluate scientific information, ideas and evidence', 25, 30, 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_CHEMISTRY', 'Chemistry')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO1', 'Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures', 30, 30, 0);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO2', 'Apply knowledge and understanding of scientific ideas, processes, techniques and procedures', 45, 45, 1);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO3', 'Analyse, interpret and evaluate scientific information, ideas and evidence', 25, 25, 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_PHYSICS', 'Physics')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO1', 'Demonstrate knowledge and understanding of scientific ideas, processes, techniques and procedures', 33, 33, 0);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO2', 'Apply knowledge and understanding of scientific ideas, processes, techniques and procedures', 42, 42, 1);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO3', 'Analyse, interpret and evaluate scientific information, ideas and evidence', 25, 25, 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_BIOLOGY', 'Biology')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Scientific investigation (SL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Research design', 6, 'State the question with its variables and enough method to repeat.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Data analysis', 6, 'Record, process and present data so a conclusion can be drawn, uncertainties included.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Conclusion', 6, 'Answer your own question against the analysis and published science, uncertainties included.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Evaluation', 6, 'Name the specific weaknesses that mattered most and improvements that address them.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Scientific investigation (HL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Research design', 6, 'State the question with its variables and enough method to repeat.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Data analysis', 6, 'Record, process and present data so a conclusion can be drawn, uncertainties included.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Conclusion', 6, 'Answer your own question against the analysis and published science, uncertainties included.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Evaluation', 6, 'Name the specific weaknesses that mattered most and improvements that address them.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_BUSINESS', 'Business management')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Business research project (SL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Business research project (HL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_CHEMISTRY', 'Chemistry')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Scientific investigation (SL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Research design', 6, 'State the question with its variables and enough method to repeat.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Data analysis', 6, 'Record, process and present data so a conclusion can be drawn, uncertainties included.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Conclusion', 6, 'Answer your own question against the analysis and published science, uncertainties included.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Evaluation', 6, 'Name the specific weaknesses that mattered most and improvements that address them.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Scientific investigation (HL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Research design', 6, 'State the question with its variables and enough method to repeat.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Data analysis', 6, 'Record, process and present data so a conclusion can be drawn, uncertainties included.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Conclusion', 6, 'Answer your own question against the analysis and published science, uncertainties included.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Evaluation', 6, 'Name the specific weaknesses that mattered most and improvements that address them.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_COMPSCI', 'Computer science')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Computational solution (SL)', 2100)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Computational solution (HL)', 2100)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_ECONOMICS', 'Economics')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Portfolio of three commentaries (SL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Diagrams', null, 'Accurate, labelled, and actually referred to in the text. A diagram nobody discusses earns little.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Terminology', null, 'Use the economic terms the article calls for, consistently, not once in the introduction.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Application and analysis', null, 'Explain the economics of this specific situation. Summarising the article is not application.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Key concept', null, 'One concept per commentary, integrated throughout — naming it and moving on forfeits the marks.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Evaluation', null, 'Stakeholders, short run versus long run, and assumptions. One-sided evaluation caps the mark.', 4);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Portfolio of three commentaries (HL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Diagrams', null, 'Accurate, labelled, and actually referred to in the text. A diagram nobody discusses earns little.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Terminology', null, 'Use the economic terms the article calls for, consistently, not once in the introduction.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Application and analysis', null, 'Explain the economics of this specific situation. Summarising the article is not application.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Key concept', null, 'One concept per commentary, integrated throughout — naming it and moving on forfeits the marks.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Evaluation', null, 'Stakeholders, short run versus long run, and assumptions. One-sided evaluation caps the mark.', 4);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_ESS', 'Environmental systems and societies')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Individual investigation (SL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Individual investigation (HL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_EXTENDED_ESSAY', 'Extended essay')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'ESSAY', 'Extended essay', 2400)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Framework for the essay', 6, 'A genuine, focused question, methods that suit the subject, and a structure that follows its conventions.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Knowledge and understanding', 6, 'Findings used to build subject knowledge, with accurate terminology and correct key concepts.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Analysis and line of argument', 6, 'Evidence-backed findings joined by a signposted thread from question to conclusion.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Discussion and evaluation', 8, 'The heaviest criterion: weigh the significance of findings and appraise your sources'' strengths and limits.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Reflection', 4, 'Assessed from the 500-word reflective statement, not the essay.', 4);
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_GEOGRAPHY', 'Geography')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO1', 'Knowledge and understanding of specified content', null, null, 0);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO2', 'Application and analysis of knowledge and understanding', null, null, 1);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO3', 'Synthesis and evaluation', null, null, 2);
  insert into public.assessment_objectives (course_template_id, code, name, weighting_min, weighting_max, ordinal)
  values (v_template, 'AO4', 'Selection, use and application of a variety of appropriate skills and techniques', null, null, 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Fieldwork report (SL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Fieldwork question and geographic context', null, 'Name the question, the place, and the syllabus theory it comes from — a question with no theory behind it caps this.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Method(s) of investigation', null, 'Say what you did and why that method suited the question, including how you sampled.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Quality and treatment of information collected', null, 'Every figure needs a title, units and a scale. Present data so it can be read, not just shown.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Written analysis', null, 'Interpret the graphs rather than describing them, and tie each finding back to the question.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Conclusion', null, 'Answer your own question directly, and only as far as the data supports.', 4);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'F', 'Evaluation', null, 'Name the confounds that actually mattered — weather, time of day, sample size — and what you would change.', 5);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Fieldwork report (HL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Fieldwork question and geographic context', null, 'Name the question, the place, and the syllabus theory it comes from — a question with no theory behind it caps this.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Method(s) of investigation', null, 'Say what you did and why that method suited the question, including how you sampled.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Quality and treatment of information collected', null, 'Every figure needs a title, units and a scale. Present data so it can be read, not just shown.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Written analysis', null, 'Interpret the graphs rather than describing them, and tie each finding back to the question.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Conclusion', null, 'Answer your own question directly, and only as far as the data supports.', 4);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'F', 'Evaluation', null, 'Name the confounds that actually mattered — weather, time of day, sample size — and what you would change.', 5);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_HISTORY', 'History')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Historical investigation (SL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Identification and evaluation of sources', 6, 'Explain how each source''s origin and purpose create its value and its limits, for this question.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Investigation', 15, 'Critical analysis with evidence and differing perspectives, ending in a reasoned judgment.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Reflection', 4, 'What your own investigation revealed about how historians work.', 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Historical investigation (HL)', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Identification and evaluation of sources', 6, 'Explain how each source''s origin and purpose create its value and its limits, for this question.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Investigation', 15, 'Critical analysis with evidence and differing perspectives, ending in a reasoned judgment.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Reflection', 4, 'What your own investigation revealed about how historians work.', 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_LANG_A_LANGLIT', 'Language A: language and literature')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Individual oral (SL)', 15)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Knowledge, understanding and interpretation', 10, 'Show what the extracts mean and what they imply about your global issue — not what happens in them.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Analysis and evaluation', 10, 'Explain how the author''s choices build the global issue. Naming a device without its effect earns nothing.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Focus and organization', 10, 'The global issue is the through-line, not a label. It should decide what you include and what you cut.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Language', 10, 'Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Individual oral (HL)', 15)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Knowledge, understanding and interpretation', 10, 'Show what the extracts mean and what they imply about your global issue — not what happens in them.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Analysis and evaluation', 10, 'Explain how the author''s choices build the global issue. Naming a device without its effect earns nothing.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Focus and organization', 10, 'The global issue is the through-line, not a label. It should decide what you include and what you cut.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Language', 10, 'Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_LANG_A_LIT', 'Language A: literature')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Individual oral (SL)', 15)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Knowledge, understanding and interpretation', 10, 'Show what the extracts mean and what they imply about your global issue — not what happens in them.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Analysis and evaluation', 10, 'Explain how the author''s choices build the global issue. Naming a device without its effect earns nothing.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Focus and organization', 10, 'The global issue is the through-line, not a label. It should decide what you include and what you cut.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Language', 10, 'Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Individual oral (HL)', 15)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Knowledge, understanding and interpretation', 10, 'Show what the extracts mean and what they imply about your global issue — not what happens in them.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Analysis and evaluation', 10, 'Explain how the author''s choices build the global issue. Naming a device without its effect earns nothing.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Focus and organization', 10, 'The global issue is the through-line, not a label. It should decide what you include and what you cut.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Language', 10, 'Accurate, precise and appropriately formal. Delivery counts — a recited script reads as flat.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_LANG_B', 'Language B')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Individual oral (SL)', 15)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Language', 12, 'Accuracy and fluency: grammar, vocabulary, pronunciation and coherence across the whole oral.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Message', 12, 'Ideas that actually engage the stimulus or extract, developed rather than listed.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Interactive skills: communication', 6, 'Move the conversation forward yourself. Answering only what you are asked caps this.', 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Individual oral (HL)', 15)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Language', 12, 'Accuracy and fluency: grammar, vocabulary, pronunciation and coherence across the whole oral.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Message', 12, 'Ideas that actually engage the stimulus or extract, developed rather than listed.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Interactive skills: communication', 6, 'Move the conversation forward yourself. Answering only what you are asked caps this.', 2);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_MATHS_AA', 'Mathematics: analysis and approaches')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Mathematical exploration (SL)', 750)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Presentation', 4, 'How the exploration is organised and whether it coheres.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Mathematical communication', 4, 'Whether the notation, terminology and representation suit the mathematics.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Personal engagement', 3, 'Evidence of engaging with the mathematics itself, not enthusiasm for the topic.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Reflection', 3, 'Reviewing and evaluating the exploration, not describing what was done.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Use of mathematics', 6, 'Mathematics at the right level, correct, and visibly understood.', 4);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Mathematical exploration (HL)', 750)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Presentation', 4, 'How the exploration is organised and whether it coheres.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Mathematical communication', 4, 'Whether the notation, terminology and representation suit the mathematics.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Personal engagement', 3, 'Evidence of engaging with the mathematics itself, not enthusiasm for the topic.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Reflection', 3, 'Reviewing and evaluating the exploration, not describing what was done.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Use of mathematics', 6, 'Mathematics at the right level, correct, and visibly understood.', 4);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_MATHS_AI', 'Mathematics: applications and interpretation')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Mathematical exploration (SL)', 750)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Presentation', 4, 'How the exploration is organised and whether it coheres.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Mathematical communication', 4, 'Whether the notation, terminology and representation suit the mathematics.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Personal engagement', 3, 'Evidence of engaging with the mathematics itself, not enthusiasm for the topic.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Reflection', 3, 'Reviewing and evaluating the exploration, not describing what was done.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Use of mathematics', 6, 'Mathematics at the right level, correct, and visibly understood.', 4);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Mathematical exploration (HL)', 750)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Presentation', 4, 'How the exploration is organised and whether it coheres.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Mathematical communication', 4, 'Whether the notation, terminology and representation suit the mathematics.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Personal engagement', 3, 'Evidence of engaging with the mathematics itself, not enthusiasm for the topic.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Reflection', 3, 'Reviewing and evaluating the exploration, not describing what was done.', 3);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'E', 'Use of mathematics', 6, 'Mathematics at the right level, correct, and visibly understood.', 4);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_PHYSICS', 'Physics')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_SL', 'Scientific investigation (SL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Research design', 6, 'State the question with its variables and enough method to repeat.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Data analysis', 6, 'Record, process and present data so a conclusion can be drawn, uncertainties included.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Conclusion', 6, 'Answer your own question against the analysis and published science, uncertainties included.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Evaluation', 6, 'Name the specific weaknesses that mattered most and improvements that address them.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_SL', 'Examinations (SL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'IA_HL', 'Scientific investigation (HL)', 600)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'A', 'Research design', 6, 'State the question with its variables and enough method to repeat.', 0);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'B', 'Data analysis', 6, 'Record, process and present data so a conclusion can be drawn, uncertainties included.', 1);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'C', 'Conclusion', 6, 'Answer your own question against the analysis and published science, uncertainties included.', 2);
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'D', 'Evaluation', 6, 'Name the specific weaknesses that mattered most and improvements that address them.', 3);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXTERNAL_HL', 'Examinations (HL)', null)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('IB_DP', 'IB_DP_TOK', 'Theory of knowledge')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  delete from public.assessment_objectives where course_template_id = v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'ESSAY', 'TOK essay', 1200)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'GLOBAL', 'Clear, coherent and critical exploration of the title', 10, 'Argue about how knowledge is made, not about the topic. Specific, named, dated examples beat general ones.', 0);

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'EXHIBITION', 'TOK exhibition', 900)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
  delete from public.rubric_criteria where assessment_type_id = v_assessment;
  insert into public.rubric_criteria (assessment_type_id, code, name, marks, guidance, ordinal)
  values (v_assessment, 'GLOBAL', 'How TOK manifests in the world around us', 10, 'Three specific objects, each with its own real-world context, each tied explicitly to the prompt.', 0);
end $$;
