-- 0025_seed_curriculum
--
-- Generated by scripts/curriculum/gen.py — do not edit by hand. Edit
-- scripts/curriculum/data/*.json and regenerate, or the file and the database
-- drift and the repo stops describing what is deployed.
--
-- This is what makes a generated plan curriculum-aware. `breakdown` looks up an
-- assessment type by the id the client sends and grounds the prompt in what that
-- component actually is — how long the paper is, what it is worth, what the
-- assessment objectives reward.
--
-- Read-only reference data: every table here already carries a read-all policy
-- for signed-in users and no write grant, so seeding adds no new attack surface.
--
-- Idempotent by design. It re-runs whenever the corpus grows.

-- Curricula. A-level is split by board because the boards genuinely
-- assess the same subject differently; treating them as one would be wrong.
insert into public.curricula (code, name) values ('A_LEVEL_AQA', 'A-Level (AQA)')
  on conflict (code) do update set name = excluded.name;

-- Subjects, their components, and their assessment objectives.

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_BIOLOGY', 'Biology')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_CHEMISTRY', 'Chemistry')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;

do $$
declare v_template uuid; v_assessment uuid;
begin
  insert into public.course_templates (curriculum_code, code, name)
  values ('A_LEVEL_AQA', 'AQA_ALEVEL_PHYSICS', 'Physics')
  on conflict (curriculum_code, code) do update set name = excluded.name
  returning id into v_template;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_1', 'Paper 1', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_2', 'Paper 2', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;

  insert into public.assessment_types (course_template_id, code, name, typical_minutes)
  values (v_template, 'PAPER_3', 'Paper 3', 120)
  on conflict (course_template_id, code) do update
    set name = excluded.name, typical_minutes = excluded.typical_minutes
  returning id into v_assessment;
end $$;
